# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='published_date',
        ),
    ]
