# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
