# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20200324_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensity',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
