# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20200324_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
