# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-15 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20200408_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffeecomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='coffee.Coffee'),
        ),
    ]
